name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build-wii:
    name: Build for Nintendo Wii
    runs-on: ubuntu-latest
    container: ghcr.io/extremscorner/libogc2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update -y && sudo apt-get install g++ -y

      - name: Configure
        run: cmake -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/Wii.cmake" -DBUILD_EXAMPLE=ON -S . -B build

      - name: Build
        run: cmake --build build

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install/gcovr

      - name: Install compiler and dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install build-essential cmake \
            valgrind

      - name: Configure
        run: cmake -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Build
        run: cmake --build build

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -T memcheck

      - name: Collect coverage
        working-directory: ${{github.workspace}}/build
        run: make check-code-coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{github.workspace}}/build/check-code-coverage/



